### ISSUE TITLE
Fork mode

### ISSUE THREAD

**Issue by cav94mat** [cav94mat/docker-maintenance#6]
In a `docker-compose.yml` stack similar to:

```yaml
version: "2"
services:
  hello:
    image: hello-world
  hello-build:
    image: cav94mat/hello
    build: ./hello/src
  docker-maintenance:
    command: --clean --recurse-one --no-pull ${PWD}
    image: cav94mat/docker-maintenance
    environment:
      DEBUG: 1
      SCHEDULE: '0 4 * * *'
      TZ: 'Europe/Rome'
    volumes:
      - '${PWD}/:${PWD}:z'
      - '/var/run/docker.sock:/var/run/docker.sock:z'
```

The service `docker-maintenance` fails to perform the maintenance operation, since the associated container gets removed but fails to be recreated.

**Expected behavior**:  
The `docker-maintenance` container should be recreated when the underlying image (`cav94mat/docker-maintenance`) was updated by a pull or sideload.

**Solution**:  
When the maintenance container is part of the current stack, an external container is to be spawned, and the maintenance operations after the pull, sideload and build stages should continue in there (forking mode).

* [x] Introduce the `--fork` and `--no-fork` options to manually enforce or suppress forking.
* [x] Introduce the `--no-recurse` flag to suppress recursion.
* [x] Automatically detect wether forking should be used, if neither `--fork` or `--no-fork` are specified, by comparing the ID of each contasiner in the target stack with the running container ID:
  * [x] Assuming the hostname *can* be the short container ID, if the length is >= 12.
  * [x] Assuming that a [string comprising the full container ID](https://stackoverflow.com/questions/20995351/how-can-i-get-docker-linux-container-information-from-within-the-container-itsel) can be generated.
* [x] If forking is requested, start a container and wait for its completion (`docker logs -f`):
  * [x] Bind-mounting he present stack directory (`$PWD:$PWD`)
  * [x] Bind-mounting he present docker sock file (also parsing `$DOCKER_HOST`)
  * [x] Using the image specified at compile time (*/make.sh*) in the `$fork_image` constant,
  * [x] Passing the entire environment of the host,
  * [x] Overriding the environment with `ON_START=1 ON_SCHEDULE= SCHEDULE=`.
  * [x] Appending the `--no-pull --no-sideload --no-build --no-recurse --no-fork` options.
  * [x] Specifying only the present stack.
* [x] Introduce the variable `$ON_SCHEDULE` (in replacement of `$SCHEDULE`, but preserving retro-compatibility) in the entrypoint, in order to plan maintenances using a cron expression.
* [x] Introduce the variable `$ON_START` to run maintenance at the container startup, when `$ON_SCHEDULE, $SCHEDULE` is also specified.
